### ISSUE TITLE
uploading code via docker to 328P uC not working

### ISSUE THREAD

**Issue by hanhanhan-kim** [tom-f-oconnell/olfactometer#2]
When trying to run `sudo docker run -i --device=/dev/ttyUSB0 tom0connell/olfactometer -p /dev/ttyUSB0 < example.yaml` to an Arduino Nano (328P), I get the following output in the terminal:
```
Reading config from stdin
Baud rate (parsed from Arduino sketch): 115200
Connected
```
The terminal output hangs at `Connected`. The only way to proceed is to ctrl+c and kill the command.

**Comment by tom-f-oconnell** [comment]
Could you include the `-u` flag in the arguments to `olfactometer`? Maybe the code just isn't uploaded?

**Comment by hanhanhan-kim** [comment]
Looks like I just had to pull the most recent version from docker with `sudo docker pull tom0connell/olfactometer` and run with the `-u` flag like suggested. I ran the following command with the most recent docker image and it worked:
`sudo docker run -i --device=/dev/ttyUSB0 tom0connell/olfactometer -p /dev/ttyUSB0 -u -f arduino:avr:nano:cpu=atmega328 < example.yaml`
Thanks!
